In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ner_datasetreference.csv', encoding='ISO-8859-1')
df.head()

Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [3]:
df.POS.value_counts()

NN      145807
NNP     131426
IN      120996
DT       98454
JJ       78412
NNS      75840
.        47831
VBD      39379
,        32757
VBN      32328
VBZ      24960
CD       24695
VB       24211
CC       23716
TO       23061
RB       20252
VBG      19125
VBP      16158
PRP      13318
POS      11257
PRP$      8655
MD        6973
``        3728
WDT       3698
JJS       3034
JJR       2967
WP        2542
NNPS      2521
RP        2490
WRB       2184
$         1149
RBR       1055
:          795
RRB        679
LRB        678
EX         663
RBS        296
;          214
PDT        147
WP$         99
UH          24
FW           1
Name: POS, dtype: int64

In [4]:
df['IN'] = df['POS'].apply(lambda x: 1 if x =='IN' else 0)

In [5]:
df.shape

(1048575, 5)

In [6]:
df.head()

Sentence #           Word  POS Tag  IN
0  Sentence: 1      Thousands  NNS   O   0
1          NaN             of   IN   O   1
2          NaN  demonstrators  NNS   O   0
3          NaN           have  VBP   O   0
4          NaN        marched  VBN   O   0

In [7]:
#Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Word, df.IN, test_size=0.2)


In [8]:
X_train.shape

(838860,)

In [9]:
X_test.shape

(209715,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

465643     recovery
294436       people
874834    customers
162081          the
Name: Word, dtype: object

In [17]:
type(y_train)

pandas.core.series.Series

In [18]:
y_train[:4]

465643    0
294436    0
874834    0
162081    0
Name: IN, dtype: int64

In [12]:
type(X_train.values)

numpy.ndarray

In [13]:
# Create bag of words representation using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv


<838860x25630 sparse matrix of type '<class 'numpy.int64'>'
	with 744759 stored elements in Compressed Sparse Row format>

In [14]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
X_train_cv.shape

(838860, 25630)

In [16]:
v.get_feature_names_out()[1771]

'andorra'

In [19]:
v.vocabulary_

{'recovery': 18905,
 'people': 17140,
 'customers': 6069,
 'the': 23093,
 'victory': 24553,
 'is': 12094,
 'pilots': 17381,
 'taliban': 22755,
 'to': 23305,
 'in': 11497,
 'storm': 22096,
 'touchdowns': 23430,
 'for': 9207,
 'looked': 13821,
 'bilateral': 3289,
 'scandal': 20327,
 'developing': 6756,
 'soldiers': 21510,
 'thursday': 23207,
 'wikileaks': 25089,
 'and': 1759,
 'crimes': 5914,
 'donors': 7284,
 '10': 22,
 'news': 15858,
 'california': 4051,
 'are': 2080,
 'main': 14083,
 'that': 23087,
 'effect': 7699,
 'from': 9434,
 'year': 25376,
 'monday': 15151,
 'iraqi': 12064,
 'prime': 17953,
 'before': 3037,
 'rwandans': 19984,
 'politicized': 17606,
 'new': 15845,
 'received': 18834,
 'while': 25039,
 'supplies': 22456,
 'racing': 18493,
 'truck': 23696,
 'rok': 19779,
 'stable': 21869,
 'tunes': 23758,
 'at': 2341,
 'some': 21552,
 'tune': 23757,
 'bomb': 3536,
 'of': 16282,
 'was': 24873,
 'third': 23151,
 'witnesses': 25180,
 'peace': 17061,
 'yemen': 25387,
 'underscore': 24

In [20]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
np.where(X_train_np[0]!=0)

(array([18905]),)

In [23]:
X_train_np[0][1771]

0